/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-base-table.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../iron-collapse/iron-collapse.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../paper-checkbox/paper-checkbox.d.ts" />
/// <reference path="../paper-item/paper-icon-item.d.ts" />
/// <reference path="../paper-item/paper-item-body.d.ts" />
/// <reference path="import-table-common-styles.d.ts" />
/// <reference path="import-table-mixin.d.ts" />

declare namespace UiElements {

  /**
   * Base table class. Contains methods and templates to be
   * used by other tables.
   *
   * In most canses child classes should only define their own `itemBodyTemplate`
   * property that is insterted into `<paper-item-body>` element.
   */
  class ImportBaseTable extends
    ArcComponents.ImportTableMixin(
    Object) {

    /**
     * Title of the table when using base tabel
     */
    tableTitle: string|null|undefined;
  }
}

interface HTMLElementTagNameMap {
  "import-base-table": UiElements.ImportBaseTable;
}
