/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-requests-table.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../iron-collapse/iron-collapse.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../paper-checkbox/paper-checkbox.d.ts" />
/// <reference path="../http-method-label/http-method-label.d.ts" />
/// <reference path="../paper-item/paper-icon-item.d.ts" />
/// <reference path="../paper-item/paper-item-body.d.ts" />
/// <reference path="import-table-common-styles.d.ts" />
/// <reference path="import-table-mixin.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of request objects to import.
   */
  class ImportRequestsTable extends
    ArcComponents.ImportTableMixin(
    Object) {

    /**
     * List of projects included in the import
     */
    projects: any[]|null|undefined;
    nonProjects: any[]|null|undefined;
    projectsData: any[]|null|undefined;
    _onSelectItem(e: any): void;
    _computeRequestsView(data: any): void;

    /**
     * Computes lable for a project
     */
    _computeProjectLabel(id: any, list: any): any;

    /**
     * Finds an element that has `data-source` attribute in the event path.
     *
     * @param path Event path.
     * @returns Value od the `data-source` attribute;
     */
    _findSource(path: any[]|null): String|null;
  }
}

interface HTMLElementTagNameMap {
  "import-requests-table": UiElements.ImportRequestsTable;
}
