/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-cookies-table.html
 */

/// <reference path="import-base-table.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of cookies to import.
   */
  class ImportCookiesTable extends
    ArcComponents.ImportTableMixin(
    ImportBaseTable) {
  }
}

interface HTMLElementTagNameMap {
  "import-cookies-table": UiElements.ImportCookiesTable;
}
