/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-history-table.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {ImportBaseTable} from './import-base-table.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

export {ImportHistoryTable};

declare namespace UiElements {

  /**
   * An element to display list of history objects to import.
   */
  class ImportHistoryTable extends
    ImportTableMixin(
    ImportBaseTable) {
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "import-history-table": UiElements.ImportHistoryTable;
  }
}
