/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-url-history-table.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {ImportUrlHistoryTable} from './src/ImportUrlHistoryTable.js';
