/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-auth-data-table.html
 */

/// <reference path="import-base-table.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of authorization data to import.
   */
  class ImportAuthDataTable extends
    ArcComponents.ImportTableMixin(
    ImportBaseTable) {
  }
}

interface HTMLElementTagNameMap {
  "import-auth-data-table": UiElements.ImportAuthDataTable;
}
