/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-url-history-table.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

/// <reference path="import-base-table.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of URLs hsitory to import.
   */
  class ImportUrlHistoryTable extends
    ArcComponents.ImportTableMixin(
    ImportBaseTable) {
  }
}

interface HTMLElementTagNameMap {
  "import-url-history-table": UiElements.ImportUrlHistoryTable;
}
