/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-headers-sets-table.html
 */

/// <reference path="import-base-table.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of headers sets to import.
   */
  class ImportHeadersSetsTable extends
    ArcComponents.ImportTableMixin(
    ImportBaseTable) {
  }
}

interface HTMLElementTagNameMap {
  "import-headers-sets-table": UiElements.ImportHeadersSetsTable;
}
