/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-variables-table.html
 */

/// <reference path="import-base-table.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of variables to import.
   */
  class ImportVariablesTable extends
    ArcComponents.ImportTableMixin(
    ImportBaseTable) {
  }
}

interface HTMLElementTagNameMap {
  "import-variables-table": UiElements.ImportVariablesTable;
}
