/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-base-table.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {ImportTableMixin} from './import-table-mixin.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

export {ImportBaseTable};

declare namespace UiElements {

  /**
   * Base table class. Contains methods and templates to be
   * used by other tables.
   *
   * In most canses child classes should only define their own `itemBodyTemplate`
   * property that is insterted into `<paper-item-body>` element.
   */
  class ImportBaseTable extends
    ImportTableMixin(
    Object) {

    /**
     * Title of the table when using base tabel
     */
    tableTitle: string|null|undefined;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "import-base-table": UiElements.ImportBaseTable;
  }
}
