/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-history-table.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../http-method-label/http-method-label.d.ts" />
/// <reference path="../date-time/date-time.d.ts" />
/// <reference path="import-base-table.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of history objects to import.
   */
  class ImportHistoryTable extends
    ArcComponents.ImportTableMixin(
    ImportBaseTable) {
  }
}

interface HTMLElementTagNameMap {
  "import-history-table": UiElements.ImportHistoryTable;
}
