/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   import-websocket-url-history-table.html
 */

/// <reference path="import-base-table.d.ts" />

declare namespace UiElements {

  /**
   * An element to display list of URLs hsitory to import.
   */
  class ImportWebsocketUrlHistoryTable extends
    ArcComponents.ImportTableMixin(
    ImportBaseTable) {
  }
}

interface HTMLElementTagNameMap {
  "import-websocket-url-history-table": UiElements.ImportWebsocketUrlHistoryTable;
}
