/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ImportAuthDataTable.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {ImportBaseTable} from './ImportBaseTable.js';

import {html, css} from 'lit-element';

export {ImportAuthDataTable};

declare namespace UiElements {

  /**
   * An element to display list of authorization data to import.
   */
  class ImportAuthDataTable extends ImportBaseTable {
    constructor();
    repeaterTemplate(): any;
  }
}
