/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ImportRequestsTable.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {ImportBaseTable} from './ImportBaseTable.js';

import {html, css} from 'lit-element';

export {ImportRequestsTable};

declare namespace UiElements {

  /**
   * An element to display list of request objects to import.
   */
  class ImportRequestsTable extends ImportBaseTable {

    /**
     * List of projects included in the import
     */
    projects: any[]|null|undefined;
    nonProjects: any[]|null|undefined;
    projectsData: any[]|null|undefined;
    constructor();
    render(): any;
    _dataChanged(data: any): void;
    _itemBodyContentTemplate(item: any): any;
    _itemBodyTemplate(item: any): any;
    projectsTemplate(): any;
    requestsTemplate(): any;

    /**
     * Computes lable for a project
     */
    _computeProjectLabel(id: any, list: any): any;
  }
}
