/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ImportWebsocketUrlHistoryTable.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {ImportBaseTable} from './ImportBaseTable.js';

import {html} from 'lit-element';

export {ImportWebsocketUrlHistoryTable};

declare namespace UiElements {

  /**
   * An element to display list of URLs hsitory to import.
   */
  class ImportWebsocketUrlHistoryTable extends ImportBaseTable {
    constructor();
    _itemBodyTemplate(item: any): any;
  }
}
